dist: bionic
language: node_js
node_js:
  - "lts/*"

cache:
  npm: true
  pip: true

before_install:
  - python -m pip install --quiet --upgrade pip

script:
  - npm test

deploy:
  edge: true
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  on:
    tags: true
    repo: motorro/room-populate